# .github/workflows/main.yml

name: Run JavaScript with dotenv

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run script with dotenv
        env:
          G_TOKEN: ${{ secrets.G_T }}
          G_OWNER: ${{ secrets.G_O }}
          G_REPO: ${{ secrets.G_R }}
          GMAIL_USER: ${{ secrets.G_U }}
          GMAIL_PASSWORD: ${{ secrets.G_P }}
          GMAIL_RECIEVER: ${{ secrets.G_RE }}
        run: npm start



      - name: Commit and Push Changes
        run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m "Commit message"
            git push
